import { FormEvent, useState } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { AlertTriangle, CheckCircle2, Loader2, Plus } from 'lucide-react'
import { supabase } from '@/lib/supabase'
import { brl } from '@/lib/utils'
import { calcularCondicaoComercial, type BaseComissaoParceiro } from '@/lib/financeiro'
import { Button } from '@/components/ui/button'
import { MoneyInput } from '@/components/MoneyInput'

interface Condicao {
  id:string; versao:number; status:'rascunho'|'aprovada'|'substituida'|'cancelada'
  tipo_base_receita:'valor_aprovado'|'valor_liberado'|'valor_fixo'; valor_base_previsto:number
  percentual_receita_mercurio:number; valor_receita_prevista:number
  base_comissao_parceiro:'valor_liberado'|'receita_bruta'; percentual_comissao_parceiro:number
  valor_comissao_parceiro_prevista:number; recebimento_previsto_em:string; aprovada_em:string|null; motivo_alteracao:string|null
}
const money=(v:number)=>brl(Math.round(Number(v)*100))

export function PropostaCondicaoComercial({propostaId,valorSugerido,canEdit}:{propostaId:string;valorSugerido:number;canEdit:boolean}){
  const qc=useQueryClient();const[showForm,setShowForm]=useState(false);const[base,setBase]=useState(valorSugerido);const[receitaPct,setReceitaPct]=useState(6);const[partnerBase,setPartnerBase]=useState<BaseComissaoParceiro>('receita_bruta');const[partnerPct,setPartnerPct]=useState(0)
  const query=useQuery({queryKey:['proposta-condicoes-comerciais',propostaId],queryFn:async()=>{const{data,error}=await supabase.from('proposta_condicoes_comerciais').select('id,versao,status,tipo_base_receita,valor_base_previsto,percentual_receita_mercurio,valor_receita_prevista,base_comissao_parceiro,percentual_comissao_parceiro,valor_comissao_parceiro_prevista,recebimento_previsto_em,aprovada_em,motivo_alteracao').eq('proposta_id',propostaId).order('versao',{ascending:false});if(error)throw error;return(data??[])as Condicao[]}})
  const create=useMutation({mutationFn:async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const fd=new FormData(e.currentTarget);const{error}=await supabase.rpc('proposta_condicao_comercial_criar',{p_proposta_id:propostaId,p_tipo_base_receita:String(fd.get('tipo_base')),p_valor_base:base,p_percentual_receita:receitaPct,p_base_comissao:partnerBase,p_percentual_parceiro:partnerPct,p_recebimento_previsto:String(fd.get('recebimento')),p_motivo:String(fd.get('motivo')).trim()||null});if(error)throw error},onSuccess:async()=>{setShowForm(false);await qc.invalidateQueries({queryKey:['proposta-condicoes-comerciais',propostaId]})}})
  const approve=useMutation({mutationFn:async(id:string)=>{const{error}=await supabase.rpc('proposta_condicao_comercial_aprovar',{p_condicao_id:id});if(error)throw error},onSuccess:async()=>{await Promise.all([qc.invalidateQueries({queryKey:['proposta-condicoes-comerciais',propostaId]}),qc.invalidateQueries({queryKey:['financeiro-lancamentos']}),qc.invalidateQueries({queryKey:['financeiro-resumo']})])}})
  const calculo=calcularCondicaoComercial({valorBase:base,percentualReceita:receitaPct,baseComissaoParceiro:partnerBase,percentualParceiro:partnerPct})
  if(query.isLoading)return <div className="card p-10 text-center"><Loader2 className="mx-auto h-6 w-6 animate-spin text-red-700"/></div>
  return <div className="space-y-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="mb-1 text-xs font-semibold uppercase tracking-[0.14em] text-red-700">Financeiro da proposta</p><h2 className="font-semibold text-silver-900">Receita Mercúrio e comissão do parceiro</h2><p className="text-sm text-silver-500">Este é o local em que o admin define a regra comercial específica desta proposta.</p></div>{canEdit&&!showForm&&<Button variant="primary" onClick={()=>setShowForm(true)}><Plus className="h-4 w-4"/> Nova versão</Button>}</div>
    <div className="rounded-xl border border-silver-200 bg-silver-50 p-4 text-sm text-silver-700"><strong className="text-silver-900">Como funciona:</strong> informe primeiro a receita bruta da Mercúrio; depois escolha se a comissão do parceiro incide sobre o valor liberado ou sobre essa receita. A regra só entra em vigor após aprovação.</div>
    {(query.error||create.error||approve.error)&&<div className="flex gap-2 rounded-lg border border-danger/30 bg-danger/5 p-3 text-sm text-danger"><AlertTriangle className="h-4 w-4"/>{errorMessage(query.error||create.error||approve.error)}</div>}
    {showForm&&<form onSubmit={e=>create.mutate(e)} className="card p-5"><div className="grid gap-4 md:grid-cols-3"><Field label="Base da receita"><select name="tipo_base" className="input" defaultValue="valor_aprovado"><option value="valor_aprovado">Valor aprovado</option><option value="valor_liberado">Valor liberado</option><option value="valor_fixo">Valor fixo</option></select></Field><MoneyInput label="Valor-base" value={base} onChange={setBase} required/><Field label="Receita bruta Mercúrio (%)"><input className="input" required type="number" min="0" max="100" step="0.0001" value={receitaPct} onChange={e=>setReceitaPct(Number(e.target.value))}/></Field></div>
      <div className="my-5 border-t border-silver-100 pt-5"><p className="mb-3 text-xs font-semibold uppercase tracking-wide text-silver-500">Comissão do parceiro</p><div className="grid gap-4 md:grid-cols-3"><Field label="Base de cálculo"><div className="grid grid-cols-2 rounded-lg bg-silver-100 p-1"><Toggle active={partnerBase==='valor_liberado'} onClick={()=>setPartnerBase('valor_liberado')}>Valor liberado</Toggle><Toggle active={partnerBase==='receita_bruta'} onClick={()=>setPartnerBase('receita_bruta')}>Receita bruta</Toggle></div></Field><Field label="Percentual customizado (%)"><input className="input" required type="number" min="0" max="100" step="0.0001" value={partnerPct} onChange={e=>setPartnerPct(Number(e.target.value))}/></Field><Field label="Recebimento previsto"><input className="input" required type="date" name="recebimento"/></Field></div></div>
      <Field label="Motivo / referência da condição"><input className="input" name="motivo" placeholder="Negociação, fundo ou documento de origem"/></Field>
      <div className="mt-5 grid gap-3 rounded-xl bg-silver-50 p-4 sm:grid-cols-3"><Preview label="Receita bruta" value={money(calculo.receitaBruta)}/><Preview label="Comissão do parceiro" value={money(calculo.comissaoParceiro)}/><Preview label="Margem antes dos demais custos" value={money(calculo.margemPreliminar)} danger={calculo.margemPreliminar<0}/></div>
      <div className="mt-5 flex justify-end gap-2"><Button type="button" variant="outline" onClick={()=>setShowForm(false)}>Cancelar</Button><Button type="submit" variant="primary" disabled={create.isPending}>{create.isPending&&<Loader2 className="h-4 w-4 animate-spin"/>} Salvar rascunho</Button></div></form>}
    {!query.data?.length&&!showForm?<div className="card py-16 text-center"><CheckCircle2 className="mx-auto h-10 w-10 text-silver-300"/><h3 className="mt-3 font-semibold text-silver-900">Comissão ainda não configurada</h3><p className="mx-auto mt-1 max-w-md text-sm text-silver-500">Crie uma versão para definir a receita da Mercúrio, a base de cálculo e o percentual do parceiro. Nada será calculado silenciosamente.</p>{canEdit&&<Button className="mt-5" variant="primary" onClick={()=>setShowForm(true)}><Plus className="h-4 w-4"/>Configurar comissão</Button>}</div>:query.data?.map(row=><article key={row.id} className={`card p-5 ${row.status==='aprovada'?'border-success/40':''}`}><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-wide text-silver-500">Versão {row.versao}</p><h3 className="mt-1 font-semibold text-silver-900">{row.status==='aprovada'?'Condição vigente':'Condição '+row.status}</h3></div><span className={`badge ${row.status==='aprovada'?'bg-success/15 text-success':row.status==='rascunho'?'bg-yellow-100 text-yellow-700':'bg-silver-100 text-silver-600'}`}>{row.status}</span></div><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Preview label="Valor-base" value={money(row.valor_base_previsto)}/><Preview label={`Receita Mercúrio · ${Number(row.percentual_receita_mercurio).toFixed(2)}%`} value={money(row.valor_receita_prevista)}/><Preview label={`Comissão do parceiro · ${Number(row.percentual_comissao_parceiro).toFixed(2)}% sobre ${row.base_comissao_parceiro==='receita_bruta'?'receita bruta':'valor liberado'}`} value={money(row.valor_comissao_parceiro_prevista)}/><Preview label="Margem preliminar" value={money(Number(row.valor_receita_prevista)-Number(row.valor_comissao_parceiro_prevista))}/></div>{row.status==='rascunho'&&canEdit&&<div className="mt-5 flex justify-end"><Button variant="primary" disabled={approve.isPending} onClick={()=>approve.mutate(row.id)}>Aprovar regra e gerar receita prevista</Button></div>}</article>)}
  </div>
}
function Toggle({active,onClick,children}:{active:boolean;onClick:()=>void;children:React.ReactNode}){return <button type="button" onClick={onClick} className={`btn-no-liquid rounded-md px-2 py-2 text-xs font-medium ${active?'bg-white text-silver-900 shadow-sm ring-1 ring-red-700/20':'text-silver-500 hover:text-silver-900'}`}>{children}</button>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="block text-xs font-medium text-silver-600"><span className="mb-1 block">{label}</span>{children}</label>}
function Preview({label,value,danger}:{label:string;value:string;danger?:boolean}){return <div><p className="text-xs text-silver-500">{label}</p><p className={`mt-1 font-bold ${danger?'text-danger':'text-silver-900'}`}>{value}</p></div>}
function errorMessage(e:unknown){return e instanceof Error?e.message:'Falha ao processar condição comercial.'}
